apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus-example
  namespace: monitoring
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  project: default
  source:
    repoURL: https://prometheus-community.github.io/helm-charts
    chart: prometheus
    targetRevision: 27.34.0
    helm:
      releaseName: prometheus-example
      valueFiles:
        - https://raw.githubusercontent.com/tcard404/ArgoCD-apps/main/charts/prometheus/values.yaml
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true